version: '3.8'
services:
  elasticsearch:
    container_name: es
    build:
      context: ./config/elasticsearch
    image: test_es
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - "discovery.type=single-node"
    volumes:
      # コンテナのディレクトリをvolumeへマウント
      # ボリューム名:マウント対象のパス
      - es-data:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    container_name: kibana
    build:
      context: ./config/kibana
    image: test_kibana
    ports:
      - '5601:5601'
    environment:
      - "elasticsearch.hosts=elasticsearch:10200"
    networks:
      - esnet
  api:
    container_name: es_api
    build:
      context: .
      dockerfile: ./config/go/Dockerfile
    image: test_api
    tty: true
    volumes:
      - ./src:/go/src/go-es-testcode
    ports:
      - '8090:8090'
    environment:
      GO_ENV: development
    networks:
      - esnet
volumes:
  es-data:
    # ボリューム'es-data'はlocalに保存します
    driver: local
networks:
  esnet:
