version: '3.8'
services:
  elasticsearch:
    build:
      context: ./config/elasticsearch
    image: test_es
    ports:
      - '10200:9200'
      - '10300:9300'
    environment:
      - "discovery.type=single-node"
    networks:
      - esnet
  kibana:
    build:
      context: ./config/kibana
    image: test_kibana
    ports:
      - '5701:5601'
    environment:
      - "elasticsearch.hosts=elasticsearch:10200"
    networks:
      - esnet
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./config/go/Dockerfile
    tty: true
    # volumes:
    #   - ./src:/go/src/go-es-testcode
    ports:
      - '50051:50051'
    networks:
      - esnet

networks:
  esnet: