GRPC_HOST: 
GRPC_PORT: "50051"
APP_ENV: "development"

ELASTIC_SEARCH: "http://es01:9200"
ELASTIC_INDEX_SHOP: "test-shop"
ELASTIC_INDEX_MENU: "test-menu"
ELASTIC_INDEX_SUGGEST: "test-suggest"

MAX_CONNS_PER_HOST: 30
RESPONSE_HEADER_TIMEOUT: 30
TIME_OUT: 10
KEEP_ALIVE: 10
